name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build the Docker image
        run: docker build ./src/api --file ./src/api/src/WhatTheHealth.API/Dockerfile -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ct-what-the-health-backend:$(date +%s)
      - name: Push the Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/my-docker-image

      
